### PR TITLE
Standard plot implementation

### PR DESCRIPTION
**Pull request by keli95566**

### CODE REVIEW

**Review by laureleya — APPROVED** [review]
Looks good!

**Comment by laureleya** [comment]
A minor thing: the dragging different plots with different z indices, the dragged plot is during the drag action in the background and only after drag stop in the front.

**Comment by asver12** [comment]
Except for two minor things looking good.
First: I disagree with the styling of the toolbar. Imo now there is to much visual clutter going on in it. Esp. the grey buttons get to much focus they don't deserve.
Second: Why do you need this additional nesting?
mistake

Overall I like that this approach. It keeps the store flat and is easy to comprehend.

**Comment by keli95566** [comment]
> Except for two minor things looking good.
> First: I disagree with the styling of the toolbar. Imo now there is to much visual clutter going on. Esp. the grey buttons get to much focus they don't deserve.
> Second: Why do you need this additional nesting?
> mistake
> 
> Overall I like that this approach. It keeps the store flat and is easy to comprehend.

Thank you for the feedback! :) 
I agree with you that the styling is pretty unrefined XD, it definitely needs improvement.

For the nesting, it is necessary. I assumed that in the screenshot you gave,  there is only one plot. When you have more than one item in each field,  the plot data for each plot is stored in this list. 

Screenshot 2020-08-19 at 12 03 20

**Review by laureleya — CHANGES_REQUESTED** [review]
What do you mean with Profile, Logout and my account? 
Commit 2db9ec8, file: PlotMenu.js

**Comment by keli95566** [comment]
> What do you mean with Profile, Logout and my account?
> Commit [2db9ec8](https://github.com/lumen-org/LumenReact/commit/2db9ec8993726d1183f507e64e14129cd3fd097f), file: PlotMenu.js

I have the same question XD

**Pull request merged**
